name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          # Don't include every versions. OCaml-CI already covers that
          - 4.14.x

    runs-on: ${{ matrix.os }}

    steps:
      # Clone the project
      - uses: actions/checkout@v2

      # Setup
      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Opam dependencies
        run: opam install --deps-only -t .

      - name: Self-formatting test
        run: opam exec -- dune build @fmt

      - name: Runtest
        run: opam exec -- dune runtest

      - name: Check help files
        run: opam exec -- dune build @help --auto-promote

      - name: Upload binary
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: ocamlformat-${{ runner.os }}-${{ runner.arch }}
          path: _build/install/default/bin/ocamlformat

  test-branch:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - conventional
          - ocamlformat
          - janestreet

    steps:
      # Clone the project
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch main build of ocamlformat
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: ""
          check_artifacts: true
          branch: main
          name: ocamlformat-${{ runner.os }}-${{ runner.arch }}
          path: ocamlformat-a

      - name: Fetch new build of ocamlformat
        uses: actions/download-artifact@v3
        with:
          name: ocamlformat-${{ runner.os }}-${{ runner.arch }}
          path: ocamlformat-b

      - name: Test ${{ matrix.profile }} profile
        run: |
          chmod +x ocamlformat-a/ocamlformat ocamlformat-b/ocamlformat
          ./tools/test_branch.sh -n -a ocamlformat-a/ocamlformat -b ocamlformat-b/ocamlformat 'profile=${{ matrix.profile }}'
        shell: bash
